import { 
    DotsThree,
    User,
    X,
    Check,
    Moon,
    Sun,
    CaretDown,
    CaretLeft,
    ChatCircle,
    PaperPlaneRight,
    Eye,
    EyeSlash,
    PencilSimple,
    CaretUpDown,
    ArrowUpRight,
    Brain,
    Copy,
    ArrowLineUp as DownloadUp,
    ArrowLineDown as DownloadDown,
    FloppyDisk,
    HandPointing,
    FileMagnifyingGlass as PageSearch,
    Plus,
    PokerChip,
    Repeat,
    Barcode,
    ListMagnifyingGlass as SearchEngine,
    Gear as Setting,
    ShareNetwork,
    TrashSimple,
    Info
} from '@phosphor-icons/react'

export const icons = {
    DotsThree,
    User,
    X,
    Check,
    Moon,
    Sun,
    CaretDown,
    CaretLeft,
    ChatCircle,
    PaperPlaneRight,
    Eye,
    EyeSlash,
    PencilSimple,
    CaretUpDown,
    ArrowUpRight,
    Brain,
    Copy,
    DownloadUp,
    DownloadDown,
    FloppyDisk,
    HandPointing,
    PageSearch,
    Plus,
    PokerChip,
    Repeat,
    Barcode,
    SearchEngine,
    Setting,
    ShareNetwork,
    TrashSimple,
    Info
};

export type IconName = keyof typeof icons;

export const getIcon = (name: IconName) => icons[name];