export declare const icons: {
    DotsThree: import("@phosphor-icons/react").Icon;
    User: import("@phosphor-icons/react").Icon;
    X: import("@phosphor-icons/react").Icon;
    Check: import("@phosphor-icons/react").Icon;
    Moon: import("@phosphor-icons/react").Icon;
    Sun: import("@phosphor-icons/react").Icon;
    CaretDown: import("@phosphor-icons/react").Icon;
    CaretLeft: import("@phosphor-icons/react").Icon;
    ChatCircle: import("@phosphor-icons/react").Icon;
    PaperPlaneRight: import("@phosphor-icons/react").Icon;
    Eye: import("@phosphor-icons/react").Icon;
    EyeSlash: import("@phosphor-icons/react").Icon;
    PencilSimple: import("@phosphor-icons/react").Icon;
    CaretUpDown: import("@phosphor-icons/react").Icon;
    ArrowUpRight: import("@phosphor-icons/react").Icon;
    Brain: import("@phosphor-icons/react").Icon;
    Copy: import("@phosphor-icons/react").Icon;
    DownloadUp: import("@phosphor-icons/react").Icon;
    DownloadDown: import("@phosphor-icons/react").Icon;
    FloppyDisk: import("@phosphor-icons/react").Icon;
    HandPointing: import("@phosphor-icons/react").Icon;
    PageSearch: import("@phosphor-icons/react").Icon;
    Plus: import("@phosphor-icons/react").Icon;
    PokerChip: import("@phosphor-icons/react").Icon;
    Repeat: import("@phosphor-icons/react").Icon;
    Barcode: import("@phosphor-icons/react").Icon;
    SearchEngine: import("@phosphor-icons/react").Icon;
    Setting: import("@phosphor-icons/react").Icon;
    ShareNetwork: import("@phosphor-icons/react").Icon;
    TrashSimple: import("@phosphor-icons/react").Icon;
    Info: import("@phosphor-icons/react").Icon;
    WarningDiamond: import("@phosphor-icons/react").Icon;
    Warning: import("@phosphor-icons/react").Icon;
    CheckCircle: import("@phosphor-icons/react").Icon;
};
export type IconName = keyof typeof icons;
export declare const getIcon: (name: IconName) => import("@phosphor-icons/react").Icon;
