export declare const icons: {
    ArrowVertical: any;
    ArrowUpRight: any;
    Brain: any;
    ChatLines: any;
    Copy: any;
    DownloadUp: any;
    DownloadDown: any;
    EditPencil: any;
    FloppyDisk: any;
    HalfMoon: any;
    MoreHoriz: any;
    NavArrowLeft: any;
    NavArrowDown: any;
    OpenSelectHand: any;
    PageSearch: any;
    Plus: any;
    Pokeball: any;
    Repeat: any;
    Scanning: any;
    SearchEngine: any;
    SendMail: any;
    Settings: any;
    ShareAndroid: any;
    Trash: any;
    Xmark: any;
};
export type IconName = keyof typeof icons;
export declare const getIcon: (name: IconName) => any;
